/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gyanendranarayan' at '3/31/16 10:50 PM' with Gradle 2.9
 *
 * @author gyanendranarayan, @date 3/31/16 10:50 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
